-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Job"
(
    id integer NOT NULL,
    "jobTitle" character varying,
    experience integer,
    wage integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Employee"
(
    id integer NOT NULL,
    "passportId" character varying NOT NULL,
    "fullName" character varying NOT NULL,
    sex character varying NOT NULL,
    job_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Room"
(
    id integer NOT NULL,
    "roomNumber" integer,
    beds integer,
    class character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Reception"
(
    id integer NOT NULL,
    "deskCount" integer NOT NULL,
    "freeRooms" integer NOT NULL,
    "freeAdmins" integer NOT NULL,
    cleaning_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Guest"
(
    id integer NOT NULL,
    "passportId" character varying NOT NULL,
    "fullName" character varying NOT NULL,
    sex character varying NOT NULL,
    room_id integer NOT NULL,
    reception_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Luggage"
(
    id integer NOT NULL,
    type integer,
    amount integer,
    weight integer,
    guest_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Employee_Room"
(
    id integer NOT NULL,
    "Employee_id" integer NOT NULL,
    "Room_id" integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Employee"
    ADD CONSTRAINT job_id FOREIGN KEY (job_id)
    REFERENCES public."Job" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reception"
    ADD CONSTRAINT cleaning_id FOREIGN KEY (cleaning_id)
    REFERENCES public."Employee_Room" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Guest"
    ADD CONSTRAINT room_id FOREIGN KEY (room_id)
    REFERENCES public."Room" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Guest"
    ADD CONSTRAINT reception_id FOREIGN KEY (reception_id)
    REFERENCES public."Reception" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Luggage"
    ADD CONSTRAINT guest_id FOREIGN KEY (guest_id)
    REFERENCES public."Guest" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employee_Room"
    ADD CONSTRAINT room_id FOREIGN KEY ("Room_id")
    REFERENCES public."Room" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Employee_Room"
    ADD FOREIGN KEY ("Employee_id")
    REFERENCES public."Employee" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;