# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/university/BSUIR/BSUIR_labs/7_term/APVMSiS/lab1/lab1.cache/wt [current_project]
set_property parent.project_path E:/university/BSUIR/BSUIR_labs/7_term/APVMSiS/lab1/lab1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.3 [current_project]
set_property ip_output_repo e:/university/BSUIR/BSUIR_labs/7_term/APVMSiS/lab1/lab1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib E:/university/BSUIR/BSUIR_labs/7_term/APVMSiS/lab1/lab1.srcs/sources_1/new/MUX8TO1_seq.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top MUX8TO1_seq -part xc7a200tfbg676-2


write_checkpoint -force -noxdef MUX8TO1_seq.dcp

catch { report_utilization -file MUX8TO1_seq_utilization_synth.rpt -pb MUX8TO1_seq_utilization_synth.pb }
