//
// Created by Ivan on 19.10.2021.
//

#ifndef LAB8_MULTIPLICITY_EXCEPTIONS_MULTIPLICITY_H
#define LAB8_MULTIPLICITY_EXCEPTIONS_MULTIPLICITY_H


class Multiplicity {

};


#endif //LAB8_MULTIPLICITY_EXCEPTIONS_MULTIPLICITY_H
